repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-symlinks
    -   id: debug-statements
    -   id: fix-encoding-pragma
    -   id: detect-private-key
    -   id: check-executables-have-shebangs
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: [--config=pyproject.toml]
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
    -   id: pycln
        args: [--config=pyproject.toml]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]
-   repo: https://github.com/PyCQA/docformatter
    rev: v1.5.1
    hooks:
    -   id: docformatter
        files: "^torchfl/.+"
        exclude: ^torchfl/(__pycache__/.+|data/.+|tests/.+|docs/.+)$
        args: [--config pyproject.toml]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        language_version: python3.10
        files: "^torchfl/.+"
        exclude: ^torchfl/(__pycache__/.+|data/.+|tests/.+|docs/.+)$
        args: [--config-file=pyproject.toml]
        additional_dependencies:
          - "numpy"
          - "pytorch_lightning"
          - "torch"
          - "torchvision"
-   repo: https://github.com/PyCQA/doc8
    rev:  v1.1.1
    hooks:
        - id: doc8
          name: doc8
          description: This hook runs doc8 for linting docs
          entry: python -m doc8
          language: python
          files: "\\.(rst)$"
          require_serial: true
          args: [--config=pyproject.toml]
# -   repo: https://github.com/charliermarsh/ruff-pre-commit
#     rev: "v0.0.246"
#     hooks:
#       - id: ruff
#         language_version: python3.10
#         args: [--fix, --exit-non-zero-on-fix]
#         exclude: ^torchfl/(__pycache__/.+|data/.+|tests/.+|docs/.+)$
