repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-symlinks
    -   id: debug-statements
    -   id: fix-encoding-pragma
    -   id: detect-private-key
    -   id: check-executables-have-shebangs
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
