name: pytest-datamodules

on:
  pull_request:
    branches:
      - "master"

jobs:
  test-datamodules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v1
      - name: Verify Changed Files
        uses: tj-actions/changed-files@v17.2
        id: verify-changed-datamodules
        with:
          files: |
            tests/datamodules/test_cifar.py
            tests/datamodules/test_emnist.py
            tests/datamodules/test_fashionmnist.py
            torchfl/datamodules/cifar.py
            torchfl/datamodules/emnist.py
            torchfl/datamodules/fashionmnist.py
      - name: Set up Python ${{ matrix.python-version }} if files were changed
        uses: actions/setup-python@v2
        if: steps.verify-changed-datamodules.outputs.any_changed == 'true'
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        if: steps.verify-changed-datamodules.outputs.any_changed == 'true'
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest coverage
          python -m pip install -r requirements_dev.txt
      - name: PyTest for datamodules
        if: steps.verify-changed-datamodules.outputs.any_changed == 'true'
        run: |
          coverage run -m pytest tests/datamodules/
          coverage report --fail-under 80 tests/datamodules/*.py
