name: pytest

on:
  push:
    paths:
      - "torchfl/"
      - "tests/"
  pull_request:
    branches:
      - "master"
    paths:
      - "torchfl/"
      - "tests/"

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: PyTest with tox
        run: tox -e py39
