name: pytest-datamodules

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Changed Datamodules
        uses: actions/cache@v3
        id: changed-datamodules
        with:
          path: tests/datamodules
          key: hashFiles('torchfl/datamodules/*')
  test-datamodules:
    runs-on: ubuntu-latest
    needs: changedfiles
    strategy:
      matrix:
        python-version: ["3.10"]
    if: ${{needs.changedfiles.changed-datamodules.outputs.cache-hit != 'true'}}
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install dependencies
        run: |
          poetry install
      - name: PyTest for datamodules
        run: |
          poetry run pytest tests/datamodules/
