name: pytest-datamodules

on:
  pull_request:
    branches:
      - master

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      datamodules: ${{ steps.changes.outputs.datamodules }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.sha }} | xargs)"
          echo "::set-output name=datamodules::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.sha }} | grep -E "tests/datamodules/|torchfl/datamodules/" | xargs)"
  test-datamodules:
    runs-on: ubuntu-latest
    needs: changedfiles
    strategy:
      matrix:
        python-version: ["3.9"]
    if: ${{needs.changedfiles.outputs.datamodules}}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }} if files were changed
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest coverage
          python -m pip install -r requirements_dev.txt
      - name: PyTest for datamodules
        run: |
          coverage run -m pytest tests/datamodules/
          coverage report --fail-under 80 tests/datamodules/*.py
