name: pytest-models

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Changed Models
        uses: actions/cache@v3
        id: changed-models
        with:
          path: tests/models
          key: hashFiles('torchfl/models/sota/*')
    outputs:
      models-cache-hit: ${{ steps.changed-models.outputs.cache-hit }}

  test-models:
    name: "Test changed model files."
    runs-on: ubuntu-latest
    needs: changedfiles
    strategy:
      matrix:
        python-version: ["3.10"]
    if: ${{needs.changedfiles.outputs.models-cache-hit != 'true'}}
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install dependencies
        run: |
          poetry install
      - name: PyTest for models
        run: |
          poetry run pytest tests/models/
