name: pytest-datamodules

on:
  pull_request:
    branches:
      - "master"

jobs:
  test-datamodules-cifar:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v1
      - name: Verify Changed Files
        uses: tj-actions/verify-changed-files@v8.8
        id: verify-changed-datamodules-cifar
        with:
          files: |
            tests/datamodules/test_cifar.py
            torchfl/datamodules/cifar.py
      - name: Set up Python ${{ matrix.python-version }} if files were changed
        uses: actions/setup-python@v2
        if: steps.verify-changed-datamodules-cifar.outputs.files_changed == 'true'
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest coverage
          python -m pip install -r requirements_dev.txt
      - name: PyTest for datamodules
        run: |
          coverage run -m pytest tests/datamodules/test_cifar.py
          coverage report --fail-under 80 tests/datamodules/test_cifar.py

  test-datamodules-emnist:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v1
      - name: Verify Changed Files
        uses: tj-actions/verify-changed-files@v8.8
        id: verify-changed-datamodules-emnist
        with:
          files: |
            tests/datamodules/test_emnist.py
            torchfl/datamodules/emnist.py
      - name: Set up Python ${{ matrix.python-version }} if files were changed
        uses: actions/setup-python@v2
        if: steps.verify-changed-datamodules-emnist.outputs.files_changed == 'true'
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest coverage
          python -m pip install -r requirements_dev.txt
      - name: PyTest for datamodules
        run: |
          coverage run -m pytest tests/datamodules/test_emnist.py
          coverage report --fail-under 80 tests/datamodules/test_emnist.py

  test-datamodules-fashionmnist:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v1
      - name: Verify Changed Files
        uses: tj-actions/verify-changed-files@v8.8
        id: verify-changed-datamodules-fashionmnist
        with:
          files: |
            tests/datamodules/test_fashionmnist.py
            torchfl/datamodules/fashionmnist.py
      - name: Set up Python ${{ matrix.python-version }} if files were changed
        uses: actions/setup-python@v2
        if: steps.verify-changed-datamodules-fashionmnist.outputs.files_changed == 'true'
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest coverage
          python -m pip install -r requirements_dev.txt
      - name: PyTest for datamodules
        run: |
          coverage run -m pytest tests/datamodules/test_fashionmnist.py
          coverage report --fail-under 80 tests/datamodules/test_fashionmnist.py
